package com.fzanutto.dota2heroes.model

data class HeroDTO(
    val id: Int,
    val name: String,
    val localized_name: String,
    val primary_attr: String,
    val attack_type: String,
    val roles: List<String>,
    val img: String,
    val icon: String,
    val base_health: Int,
    val base_health_regen: Double,
    val base_mana: Int,
    val base_mana_regen: Double,
    val base_armor: Double,
    val base_mr: Int,
    val base_attack_min: Int,
    val base_attack_max: Int,
    val base_str: Int,
    val base_agi: Int,
    val base_int: Int,
    val str_gain: Double,
    val agi_gain: Double,
    val int_gain: Double,
    val attack_range: Int,
    val projectile_speed: Int,
    val attack_rate: Double,
    val move_speed: Int,
    val turn_rate: Any,
    val cm_enabled: Boolean,
    val legs: Int,
    val hero_id: Int,
    val turbo_picks: Int,
    val turbo_wins: Int,
    val pro_ban: Int,
    val pro_win: Int,
    val pro_pick: Int,
    val `1_pick`: Int,
    val `1_win`: Int,
    val `2_pick`: Int,
    val `2_win`: Int,
    val `3_pick`: Int,
    val `3_win`: Int,
    val `4_pick`: Int,
    val `4_win`: Int,
    val `5_pick`: Int,
    val `5_win`: Int,
    val `6_pick`: Int,
    val `6_win`: Int,
    val `7_pick`: Int,
    val `7_win`: Int,
    val `8_pick`: Int,
    val `8_win`: Int,
    val null_pick: Int,
    val null_win: Int
) {
    fun toHero(): Hero {
        return Hero(
            id,
            localized_name,
            PrimaryAttribute.fromString(primary_attr),
            roles,
            legs, "https://api.opendota.com$img",
            "https://api.opendota.com$icon"
        )
    }
}